# Generated by Django 4.1.2 on 2022-12-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cartmodel_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='totalprice',
            field=models.CharField(default='', max_length=200),
        ),
    ]
