# Generated by Django 4.1.2 on 2023-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cartmodel_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('usercontact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('orederamt', models.CharField(max_length=50)),
                ('pymentmethod', models.CharField(default=None, max_length=50)),
                ('transcationid', models.TextField(default=None)),
            ],
        ),
    ]
