# Generated by Django 4.1.2 on 2023-01-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='paymentvia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
